version: "3.9"

services:
python:
 image: ghcr.io/jutsteex/task1111:1.0
 container_name: task1111
 restart: unless-stopped
 ports:
  - 3030:80
node:
 image: ghcr.io/jutsteex/task1111:1.0
 container_name: task1111-2
 restart: unless-stopped
 port:
  - 80:3030
